### ISSUE TITLE
Could I please have my amulet of the night back? 

### ISSUE THREAD

**Issue by Raezar** [RTRGitHub/RTRRedux#356] opened 2016-02-18 15:53 UTC
Died after walking thru a portal, lost my amulet of night, and a couple rings.  Dont remember what the rings were, so they must not have been important lol, but my AMULET is my preciousss.

**Comment by Solidflip** [comment] 2016-02-18 18:23
dupe of #355

**Closed as completed by Solidflip** 2016-02-18 18:23 UTC
Labels: duplicate
