### ISSUE TITLE
Server crashing when I log in ( Work_work)

### ISSUE THREAD

**Issue by Work-work** [RTRGitHub/RTRRedux#163] opened 2015-07-16 02:14 UTC
No sure what is going on, I live in a desert area just across from someone so it might not be a chunk, but it is probably something wrong with my inventory?

**Comment by Abouttabs** [comment] 2015-07-16 05:55
do you use logistic pipes?
crashlog points me to them, but I cant find any in the location specified by said log...

**Comment by Abouttabs** [comment] 2015-07-16 06:21
I will need your coords, according to the log you are spawning in a forested area (not a desert), could you please give me coords of where you are so I can investigate more? Ty...

**Comment by Solidflip** [comment] 2015-07-16 15:35
I fixed this issue temporarily by deleting the item. He can now log in.

**Comment by Solidflip** [comment] 2015-07-16 15:46
Issue caused by RR3 using an unstable build of BC7, mod author suggests downgrading to 0.9.1.

**Comment by Solidflip** [comment] 2015-07-16 15:57
https://github.com/RS485/LogisticsPipes/issues/727 for refrence

**Comment by Solidflip** [comment] 2015-07-16 16:12
Issue fixed by removing logistic pipes.

**Closed as completed by Solidflip** 2015-07-16 16:12 UTC
